
# The aim here is to get the most efficient use of screen space, especially
# for those who are perhaps not so good at reading tiny fonts.  The key
# observation is that the probability of a column having any non-blank
# character in it declines rapidly after around column 65, which means columns
# out to 100 are largely wasted screen space.
#
# With 80 cols and 2 char indent, the number of lines increases only about 5%
# compared to the default 100 cols and 4 char indent, yet it becomes feasible
# to have 3 windows rather than 2 side-by-side on a typical 27 inch monitor,
# hence increasing the total amount of code visible.  It's also easier on
# small screen devices (laptops).

fn_args_layout = "Compressed"
max_width = 80
tab_spaces = 2
use_small_heuristics = "Max"
use_field_init_shorthand = true

# These seem useful, but alas are not currently supported in the stable
# toolchain.

#unstable_features = true
#
#blank_lines_upper_bound = 2
#comment_width = 80
#format_strings = true
#merge_imports = true
#overflow_delimited_expr = true
#struct_field_align_threshold = 5
#spaces_around_ranges = true
#trailing_comma = "Never"
#where_single_line = true
#wrap_comments = true
