name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run:  git submodule update --init --recursive
    - name: Build
      run: cargo build --verbose --frozen
    - name: Run tests
      run: cargo test --verbose
